# Generated by Django 4.1 on 2022-10-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UVGV_FMS", "0003_flutteruser"),
    ]

    operations = [
        migrations.RemoveField(model_name="flutteruser", name="id",),
        migrations.AlterField(
            model_name="flutteruser",
            name="UserName",
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
