# Generated by Django 4.1 on 2022-10-25 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UVGV_FMS", "0004_remove_flutteruser_id_alter_flutteruser_username"),
    ]

    operations = [
        migrations.AlterModelOptions(name="flutteruser", options={},),
    ]
