# Generated by Django 3.2 on 2022-10-31 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UVGV_FMS', '0008_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='UserName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='UVGV_FMS.flutteruser', verbose_name='Data Collector'),
        ),
    ]
