# Generated by Django 3.2 on 2022-11-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UVGV_FMS', '0010_auto_20221120_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='pickupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
