# Generated by Django 3.2 on 2022-11-24 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UVGV_FMS', '0011_pickupload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickupload',
            options={'ordering': ['image']},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ('saved',)},
        ),
    ]
