# Generated by Django 3.2 on 2022-11-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UVGV_FMS', '0012_auto_20221124_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
